[package]
name = "gmod_rust"
version = "0.1.0"
authors = ["wyozi <joonasmertanen@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
